### ISSUE TITLE
Getting Started documentation confused job_name

### ISSUE THREAD

**Issue by teresafds** [awsdocs/amazon-transcribe-developer-guide#4]
In the getting-started examples, the "job name" doesn't follow the pattern `^[0-9a-zA-Z._-]+`. This leads to getting error on the aws cli (and python) because of the wrong transcriptionjobname

**Comment by cbigham** [comment]
Thanks for your comment on the Amazon Transcribe documentation. I understand that you get an error when you are using the CLI and Python examples because the transcription job name is invalid. Having an invalid job name is by design, It encourages the developer to include a job name relevant to their application instead of a generic name. It's the same principle as using "S3 bucket" for the bucket name -- the name is obviously invalid so the developer has to put in the proper bucket to run the job.

Thanks for you comment on the Amazon Transcribe documentation. I appreciate the feed back.

Chuck BIgham
AWS Developer Documentation
